import React, { useEffect, useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { setData } from "../redux/dataSlice";
import Head from "next/head";
import Image from "next/image";
import { dataLocal } from "../../localdata";

const URL = process.env.NEXT_PUBLIC_URL;

export default function Home() {
  const dispatch = useDispatch();

  const data = useSelector((state) => state.data.value);
  const input = useSelector((state) => state.input.value);
  const filter = useSelector((state) => state.filter.value);

  useEffect(() => {
    const getAllData = async () => {
      const res = await fetch(URL);
      const arrData = await res.json();
      dispatch(setData(arrData));
      console.log("Data fetched!");
    };
    getAllData();
    // dispatch(setData(dataLocal));
  }, []);

  return (
    <>
      <Head>
        <title>E-shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          {input.length >= 3
            ? filter.map((item, index) => {
                return (
                  <div className="item-wrap" key={index}>
                    <div className="img-wrap">
                      {item.image ? (
                        <Image
                          src={item.image}
                          alt={item.title}
                          layout="fill"
                        />
                      ) : (
                        <Image src="/03.png" alt={item.title} layout="fill" />
                      )}
                    </div>
                    <h2 className="title">{item.title}</h2>
                    <p className="desc">{item.description}</p>
                    <span className="price">{item.price} Р</span>
                  </div>
                );
              })
            : data.map((item, index) => {
                return (
                  <div className="item-wrap" key={index}>
                    <div className="img-wrap">
                      {item.image ? (
                        <Image
                          src={item.image}
                          alt={item.title}
                          layout="fill"
                        />
                      ) : (
                        <Image src="/03.png" alt={item.title} layout="fill" />
                      )}
                    </div>
                    <h2 className="title">{item.title}</h2>
                    <p className="desc">
                      {item.description?.toLowerCase() || " "}
                    </p>
                    <span className="price">{item.price} Р</span>
                  </div>
                );
              })}
        </div>
      </main>
    </>
  );
}
